services:
  cintra-taskmaster:
    build: .
    container_name: cintra-taskmaster-mcp
    ports:
      - '3000:3000'
    environment:
      # Basic server configuration
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      
      # Jira configuration (base URL from environment, credentials from headers)
      - JIRA_API_URL=${JIRA_API_URL:-https://your-domain.atlassian.net}
      
      # Bitbucket configuration (workspace from environment, credentials from headers)
      - BITBUCKET_WORKSPACE=${BITBUCKET_WORKSPACE:-your-workspace}
      
      # OAuth Configuration (required for MCP Inspector)
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL:-${BASE_URL}/auth/callback}
      - ATLASSIAN_CLIENT_ID=${ATLASSIAN_CLIENT_ID}
      - ATLASSIAN_CLIENT_SECRET=${ATLASSIAN_CLIENT_SECRET}
      - MCP_CLIENT_ID=${MCP_CLIENT_ID:-${ATLASSIAN_CLIENT_ID}}
      - MCP_CLIENT_SECRET=${MCP_CLIENT_SECRET:-${ATLASSIAN_CLIENT_SECRET}}
      - JWT_SECRET=${JWT_SECRET}
      
      # Optional: Configure logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      
    restart: unless-stopped
    
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s 